
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Feb 10 03:00:49 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 3;
  public static final int ASSIGNMENT = 25;
  public static final int NUMCONST = 47;
  public static final int CASE = 12;
  public static final int NOT_EQUAL = 27;
  public static final int LPAREN = 39;
  public static final int SEMI = 36;
  public static final int GREATER = 28;
  public static final int CONTINUE = 14;
  public static final int FOR = 15;
  public static final int MINUS = 21;
  public static final int RPAREN = 40;
  public static final int AND = 33;
  public static final int OR = 32;
  public static final int COMMA = 38;
  public static final int CLASS = 4;
  public static final int INC = 34;
  public static final int DIV = 23;
  public static final int QUESTION_MARK = 46;
  public static final int LESSER = 29;
  public static final int PLUS = 20;
  public static final int IF = 7;
  public static final int EOF = 0;
  public static final int RETURN = 16;
  public static final int EQUAL = 26;
  public static final int GREATER_EQUAL = 30;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int MUL = 22;
  public static final int MOD = 24;
  public static final int IDENT = 48;
  public static final int FULL_STOP = 37;
  public static final int BREAK = 13;
  public static final int VOID = 6;
  public static final int SWITCH = 11;
  public static final int COLON = 45;
  public static final int LBRACE = 41;
  public static final int ELSE = 8;
  public static final int LSQUARE = 43;
  public static final int READ = 17;
  public static final int CHARCONST = 50;
  public static final int RSQUARE = 44;
  public static final int WHILE = 10;
  public static final int RBRACE = 42;
  public static final int BOOLCONST = 49;
  public static final int EXTENDS = 5;
  public static final int PROG = 2;
  public static final int LESSER_EQUAL = 31;
  public static final int DEC = 35;
  public static final int PRINT = 18;
  public static final int DO = 9;
}

